# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Deploy google app engine
      # You may pin to the exact commit or the version.
      # uses: vijayp23/deploy-gae-action@bfbd0510d7dd1ccc2b2537acbbd080becf418f0d
      uses: vijayp23/deploy-gae-action@1.0.2
      with:
        # Service account file
        service-account: ${{ secrets.SERVICE_ACCOUNT }}
        # Project id
        project-id: ${{ secrets.PROJECT_ID }}
        # The yaml files for the services or configurations you want to deploy
        config-files: ./src/main/appengine/app.yaml
        # The version of the app that will be created or replaced by this deployment
        service-version: # optional, default is
        # Delete versions which are not receiving any traffic
        delete-previous-versions: # optional
        # Name of the service which previous versions needs to be deleted
        service-name: # optional, default is default
        # Disables using of cache when building project
        no-cache: # optional
        # Debug action
        debug: # optional

